### ISSUE TITLE
List All Users

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge#5]

**Comment by myieye** [comment]
@hahn-kev It seems that Swagger doesn't yet play well with `IParseable`. In the UI it doesn't accept a string:

![image](https://user-images.githubusercontent.com/12587509/211610185-8b0d8512-de05-464f-ac5f-482b92d5dc80.png)

This is the best solution I can find. It requires listing each generic LfId type we use. Any thoughts?
```
builder.Services.AddSwaggerGen(c =>
{
    c.MapType<LfId<User>>(() => new OpenApiSchema { Type = "string" });
});
```

**Comment by hahn-kev** [comment]
Can you call map type like this:
`c.MapType(typeof(LfId<>))`?

**Comment by myieye** [comment]
List all Users is already implemented:

![image](https://user-images.githubusercontent.com/12587509/212685676-b90d7e42-64da-4329-842a-876ced9b7f19.png)
